# proto-file: flutter/cpp/proto/mlperf_task.proto
# proto-message: MLPerfConfig

task {
  id: "image_classification_v2"
  name: "Image Classification v2"
  min_query_count: 1024
  min_duration: 60
  max_duration: 600
  max_throughput: 1000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "local:///mlperf_datasets/imagenet/img"
      groundtruth_path: "local:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "Imagenet dataset for integration test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/assets/imagenet_tiny-groundtruth.txt"
    }
  }
  model {
    id: "MobileNetEdgeTPUv2-L"
    name: "MobileNetEdgeTPUv2-L"
    offset: 0
    image_width: 384
    image_height: 384
    num_classes: 1000
  }
}

task {
  id: "object_detection"
  name: "Object Detection"
  min_query_count: 1024
  min_duration: 60
  max_duration: 600
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: COCO
    full {
      name: "COCO 2017 validation set"
      input_path: "local:///mlperf_datasets/coco/img"
      groundtruth_path: "local:///mlperf_datasets/coco/coco_val_full.pbtxt"
    }
    lite {
      name: "Open images subset for detection"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/coco.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "Coco dataset for integration test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/datasets/coco-test.zip"
      groundtruth_path: "https://raw.githubusercontent.com/mlcommons/mobile_models/main/v1_0/assets/coco_val_tiny.pbtxt"
    }
  }
  model {
    id: "ssd_mobiledet"
    name: "SSD-MobileDET"
    offset: 1
    num_classes: 91
    image_width: 320
    image_height: 320
  }
}

task {
  id: "image_segmentation_v2"
  name: "Image Segmentation v2"
  min_query_count: 1024
  min_duration: 60
  max_duration: 600
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: ADE20K
    full {
      name: "ADE20K validation set"
      input_path: "local:///mlperf_datasets/ade20k/images"
      groundtruth_path: "local:///mlperf_datasets/ade20k/annotations"
    }
    lite {
      name: "Open images subset for segmentation"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/ade20k.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "ADE20K validation subset for integration test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/datasets/ade20k_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/datasets/ade20k_tiny_annotations.zip"
    }
  }
  model {
    id: "mosaic"
    name: "MOSAIC"
    num_classes: 31
    image_width: 512
    image_height: 512
  }
}

task {
  id: "natural_language_processing"
  name: "Language Understanding"
  min_query_count: 1024
  min_duration: 60
  max_duration: 600
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: SQUAD
    full {
      name: "Squad V1.1 validation set"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/datasets/squad_eval_mini.tfrecord"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/squad_groundtruth.tfrecord"
    }
    lite {
      name: "Squad V1.1 mini set"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/datasets/squad_eval_mini.tfrecord"
      groundtruth_path: ""
    }
    tiny {
      name: "Squad V1.1 mini set"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/datasets/squad_eval_tiny.tfrecord"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/squad_groundtruth.tfrecord"
    }
  }
  model {
    id: "mobilebert"
    name: "MobileBert"
  }
}

task {
  id: "super_resolution"
  name: "Super Resolution "
  min_query_count: 1024
  min_duration: 60
  max_duration: 600
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: SNUSR
    full {
      name: "SNUSR dataset for accuracy test"
      input_path: "local:///mlperf_datasets/snusr/lr"
      groundtruth_path: "local:///mlperf_datasets/snusr/hr"
    }
    lite {
      name: "SNUSR dataset for performance test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/datasets/snusr_lr_png.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "SNUSR dataset for integration test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/datasets/snusr_lr_png_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/datasets/snusr_hr_png_tiny.zip"
    }
  }
  model {
    id: "edsr"
    name: "EDSR"
    image_width: 960
    image_height: 540
  }
}

task {
  id: "image_classification_offline_v2"
  name: "Image Classification v2 (Offline)"
  min_query_count: 24576
  min_duration: 0
  max_duration: 0
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "Offline"
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "local:///mlperf_datasets/imagenet/img"
      groundtruth_path: "local:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "Imagenet dataset for integration test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/assets/imagenet_tiny-groundtruth.txt"
    }
  }
  model {
    id: "MobileNetEdgeTPUv2-L"
    name: "MobileNetEdgeTPUv2-L"
    offset: 0
    image_width: 384
    image_height: 384
    num_classes: 1000
  }
}

task {
  id: "image_classification"
  name: "Image Classification"
  min_query_count: 1024
  min_duration: 60
  max_duration: 600
  max_throughput: 1000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "local:///mlperf_datasets/imagenet/img"
      groundtruth_path: "local:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "Imagenet dataset for integration test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/assets/imagenet_tiny-groundtruth.txt"
    }
  }
  model {
    id: "mobilenetedgetpu_224_v1_0"
    name: "MobileNetEdgeTPU 224 1.0"
    offset: 1
    image_width: 224
    image_height: 224
    num_classes: 1000
  }
}

task {
  id: "image_classification_offline"
  name: "Image Classification (Offline)"
  min_query_count: 24576
  min_duration: 0
  max_duration: 0
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "Offline"
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "local:///mlperf_datasets/imagenet/img"
      groundtruth_path: "local:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "Imagenet dataset for integration test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/assets/imagenet_tiny-groundtruth.txt"
    }
  }
  model {
    id: "mobilenetedgetpu_224_v1_0"
    name: "MobileNetEdgeTPU 224 1.0"
    offset: 1
    image_width: 224
    image_height: 224
    num_classes: 1000
  }
}

task {
  id: "stable_diffusion"
  name: "Stable Diffusion"
  min_query_count: 5
  min_duration: 60
  max_duration: 600
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: COCOGEN
    full {
      name: "COCO validation set for Stable Diffusion"
      input_path: "https://github.com/anhappdev/tmp/releases/download/5/coco_gen_full.tfrecord"
      groundtruth_path: "local:///mlperf_models/stable-diffusion/clip_model_512x512.tflite"
    }
    lite {
      name: "COCO validation set for Stable Diffusion"
      input_path: "https://github.com/anhappdev/tmp/releases/download/5/coco_gen_test.tfrecord"
      groundtruth_path: "local:///mlperf_models/stable-diffusion/clip_model_512x512.tflite"
    }
    tiny {
      name: "COCO validation set for Stable Diffusion"
      input_path: "https://github.com/anhappdev/tmp/releases/download/2/coco_gen.tfrecord"
      groundtruth_path: "local:///mlperf_models/stable-diffusion/clip_model_512x512.tflite"
    }
  }
  model {
    id: "stable_diffusion"
    name: "StableDiffusion"
  }
}
