# proto-file: flutter/cpp/proto/mlperf_task.proto
# proto-message: MLPerfConfig

task {
  id: "image_classification"
  name: "Image Classification"
  min_query_count: 1024
  min_duration: 60
  max_throughput: 1000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "data:///mlperf_datasets/imagenet/img"
      groundtruth_path: "data:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/imagenet_val_tiny.txt"
    }
    tiny {
      name: "Imagenet dataset for instrument test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/assets/imagenet_tiny-groundtruth.txt"
    }
  }
  model {
    id: "mobilenetedgetpu_224_v1_0"
    name: "MobileNetEdgeTPU 224 1.0"
    offset: 1
    image_width: 224
    image_height: 224
    num_classes: 1000
  }
}

task {
  id: "object_detection"
  name: "Object Detection"
  min_query_count: 1024
  min_duration: 60
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: COCO
    full {
      name: "COCO 2017 validation set"
      input_path: "data:///mlperf_datasets/coco/img"
      groundtruth_path: "data:///mlperf_datasets/coco/coco_val_full.pbtxt"
    }
    lite {
      name: "Open images subset for detection"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/coco.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/coco_val_tiny.pbtxt"
    }
    tiny {
      name: "Coco dataset for instrument test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/datasets/coco-test.zip"
      groundtruth_path: "https://raw.githubusercontent.com/mlcommons/mobile_models/main/v1_0/assets/coco_val_tiny.pbtxt"
    }
  }
  model {
    id: "ssd_mobiledet"
    name: "SSD-MobileDET"
    offset: 1
    num_classes: 91
    image_width: 320
    image_height: 320
  }
}

task {
  id: "image_segmentation_v2"
  name: "v2.0 Image Segmentation"
  min_query_count: 1024
  min_duration: 60
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: ADE20K
    full {
      name: "ADE20K validation set"
      input_path: "data:///mlperf_datasets/ade20k/images"
      groundtruth_path: "data:////mlperf_datasets/ade20k/annotations"
    }
    lite {
      name: "Open images subset for segmentation"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/ade20k.zip"
      groundtruth_path: ""
    }
    tiny {
      name: "Open images subset for segmentation"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/ade20k_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/assets/ade20k-tiny-saved-output.zip"
    }
  }
  model {
    id: "mosaic"
    name: "MOSAIC"
    num_classes: 31
    image_width: 512
    image_height: 512
  }
}

task {
  id: "natural_language_processing"
  name: "Language Understanding"
  min_query_count: 1024
  min_duration: 60
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  datasets {
    type: SQUAD
    full {
      name: "Squad V1.1 validation set"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/datasets/squad_eval_mini.tfrecord"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/squad_groundtruth.tfrecord"
    }
    lite {
      name: "Squad V1.1 mini set"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/datasets/squad_eval_mini.tfrecord"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/squad_groundtruth.tfrecord"
    }
    tiny {
      name: "Squad V1.1 mini set"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/datasets/squad_eval_tiny.tfrecord"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/squad_groundtruth.tfrecord"
    }
  }
  model {
    id: "mobilebert"
    name: "MobileBert"
  }
}

task {
  id: "image_classification_offline"
  name: "Image Classification (Offline)"
  min_query_count: 24576
  min_duration: 0
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "Offline"
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "data:///mlperf_datasets/imagenet/img"
      groundtruth_path: "data:///mlperf_datasets/imagenet/imagenet_val_full.txt"
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/assets/imagenet_val_tiny.txt"
    }
    tiny {
      name: "Imagenet dataset for instrument test"
      input_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/datasets/imagenet_tiny.zip"
      groundtruth_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/assets/imagenet_tiny-groundtruth.txt"
    }
  }
  model {
    id: "mobilenetedgetpu_224_v1_0"
    name: "MobileNetEdgeTPU 224 1.0"
    offset: 1
    image_width: 224
    image_height: 224
    num_classes: 1000
  }
}
