# proto-file: flutter/cpp/proto/mlperf_task.proto
# proto-message: MLPerfConfig

task {
  id: "image_classification_v2"
  name: "Image Classification v2"
  max_throughput: 1000
  max_accuracy: 1.0
  scenario: "SingleStream"
  runs {
    normal {
      min_query_count: 1024
      min_duration: 60
      max_duration: 600
    }
    quick {
      min_query_count: 128
      min_duration: 10
      max_duration: 60
    }
    rapid {
      min_query_count: 64
      min_duration: 6
      max_duration: 60
    }
  }
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "local:///mlperf_datasets/imagenet/img"
      input_checksum: ""
      groundtruth_path: "local:///mlperf_datasets/imagenet/imagenet_val_full.txt"
      groundtruth_checksum: ""
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v0_7/imagenet.zip"
      input_checksum: "fdcce28e06475321dc9b1c63a5539a4e"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "Imagenet dataset for integration test"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v5_0/imagenet_tiny.zip"
      input_checksum: "2cde6f1d741b9c1834db261ac6e43a6e"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v5_0/imagenet_tiny_val.txt"
      groundtruth_checksum: "086f99eff3d1b93fd41e7f35498570a7"
    }
  }
  model {
    id: "MobileNetEdgeTPUv2-L"
    name: "MobileNetEdgeTPUv2-L"
    offset: 0
    image_width: 384
    image_height: 384
    num_classes: 1000
  }
}

task {
  id: "object_detection"
  name: "Object Detection"
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  runs {
    normal {
      min_query_count: 1024
      min_duration: 60
      max_duration: 600
    }
    quick {
      min_query_count: 128
      min_duration: 10
      max_duration: 60
    }
    rapid {
      min_query_count: 64
      min_duration: 6
      max_duration: 60
    }
  }
  datasets {
    type: COCO
    full {
      name: "COCO 2017 validation set"
      input_path: "local:///mlperf_datasets/coco/img"
      input_checksum: ""
      groundtruth_path: "local:///mlperf_datasets/coco/coco_val_full.pbtxt"
      groundtruth_checksum: ""
    }
    lite {
      name: "Open images subset for detection"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v0_7/coco.zip"
      input_checksum: "c630e2ddf96a1e9482c4a9e1d4aced70"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "Coco dataset for integration test"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v3_0/coco-test.zip"
      input_checksum: "7440da62aee7043b825d3ac1c6732e0a"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v1_0/coco_val_tiny.pbtxt"
      groundtruth_checksum: "0bae0c934cae7fa41f178c085bf31c7b"
    }
  }
  model {
    id: "ssd_mobiledet"
    name: "SSD-MobileDET"
    offset: 1
    num_classes: 91
    image_width: 320
    image_height: 320
  }
}

task {
  id: "image_segmentation_v2"
  name: "Image Segmentation v2"
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  runs {
    normal {
      min_query_count: 1024
      min_duration: 60
      max_duration: 600
    }
    quick {
      min_query_count: 128
      min_duration: 10
      max_duration: 60
    }
    rapid {
      min_query_count: 64
      min_duration: 6
      max_duration: 60
    }
  }
  datasets {
    type: ADE20K
    full {
      name: "ADE20K validation set"
      input_path: "local:///mlperf_datasets/ade20k/images"
      input_checksum: ""
      groundtruth_path: "local:///mlperf_datasets/ade20k/annotations"
      groundtruth_checksum: ""
    }
    lite {
      name: "Open images subset for segmentation"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v0_7/ade20k.zip"
      input_checksum: "97f48388e5ca3b4f19047e0b7a062c88"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "ADE20K validation subset for integration test"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v3_1/ade20k_tiny.zip"
      input_checksum: "544a538eed16283586bd583dd39c44db"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v3_1/ade20k_tiny_annotations.zip"
      groundtruth_checksum: "a0e4b79dceac96a784b7abaa59aa76df"
    }
  }
  model {
    id: "mosaic"
    name: "MOSAIC"
    num_classes: 31
    image_width: 512
    image_height: 512
  }
}

task {
  id: "natural_language_processing"
  name: "Language Understanding"
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  runs {
    normal {
      min_query_count: 1024
      min_duration: 60
      max_duration: 600
    }
    quick {
      min_query_count: 128
      min_duration: 10
      max_duration: 60
    }
    rapid {
      min_query_count: 64
      min_duration: 6
      max_duration: 60
    }
  }
  datasets {
    type: SQUAD
    full {
      name: "Squad V1.1 validation set"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v1_0/squad_eval_mini.tfrecord"
      input_checksum: "3c9a1c4c373037889938d4b13d41f4c2"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v1_0/squad_groundtruth.tfrecord"
      groundtruth_checksum: "f9d6d209ec9a05a522749a6bd597a75c"
    }
    lite {
      name: "Squad V1.1 mini set"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v1_0/squad_eval_mini.tfrecord"
      input_checksum: "3c9a1c4c373037889938d4b13d41f4c2"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "Squad V1.1 mini set"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v1_0/squad_eval_tiny.tfrecord"
      input_checksum: "fa018f599d0016ed385b31aee7b00bed"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v1_0/squad_groundtruth.tfrecord"
      groundtruth_checksum: "f9d6d209ec9a05a522749a6bd597a75c"
    }
  }
  model {
    id: "mobilebert"
    name: "MobileBert"
  }
}

task {
  id: "super_resolution"
  name: "Super Resolution "
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  runs {
    normal {
      min_query_count: 1024
      min_duration: 60
      max_duration: 600
    }
    quick {
      min_query_count: 128
      min_duration: 10
      max_duration: 60
    }
    rapid {
      min_query_count: 64
      min_duration: 6
      max_duration: 60
    }
  }
  datasets {
    type: SNUSR
    full {
      name: "SNUSR dataset for accuracy test"
      input_path: "local:///mlperf_datasets/snusr/lr"
      input_checksum: ""
      groundtruth_path: "local:///mlperf_datasets/snusr/hr"
      groundtruth_checksum: ""
    }
    lite {
      name: "SNUSR dataset for performance test"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v3_1/snusr_lr_png.zip"
      input_checksum: "38bf296e38cba0a8229d946fc1a5095a"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "SNUSR dataset for integration test"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v3_1/snusr_lr_png_tiny.zip"
      input_checksum: "134e9f96e4bbd5e925093e30a4433548"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v3_1/snusr_hr_png_tiny.zip"
      groundtruth_checksum: "c8eac83e32d163552ca8e317c2dd57c3"
    }
  }
  model {
    id: "edsr"
    name: "EDSR"
    image_width: 960
    image_height: 540
  }
}

task {
  id: "image_classification_offline_v2"
  name: "Image Classification v2 (Offline)"
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "Offline"
  runs {
    normal {
      min_query_count: 24576
      min_duration: 0
      max_duration: 0
    }
    quick {
      min_query_count: 2457
      min_duration: 0
      max_duration: 0
    }
    rapid {
      min_query_count: 64
      min_duration: 0
      max_duration: 0
    }
  }
  datasets {
    type: IMAGENET
    full {
      name: "Imagenet classification validation set"
      input_path: "local:///mlperf_datasets/imagenet/img"
      input_checksum: ""
      groundtruth_path: "local:///mlperf_datasets/imagenet/imagenet_val_full.txt"
      groundtruth_checksum: ""
    }
    lite {
      name: "Open images subset for classification"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v0_7/imagenet.zip"
      input_checksum: "fdcce28e06475321dc9b1c63a5539a4e"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "Imagenet dataset for integration test"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v0_7/imagenet_tiny.zip"
      input_checksum: "42cb83d80d0341d6719d68b32322adf2"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v3_0/imagenet_tiny-groundtruth.txt"
      groundtruth_checksum: "cc6d83ca25daeb2475f36c079e53bc26"
    }
  }
  model {
    id: "MobileNetEdgeTPUv2-L"
    name: "MobileNetEdgeTPUv2-L"
    offset: 0
    image_width: 384
    image_height: 384
    num_classes: 1000
  }
}

task {
  id: "llm"
  name: "LLM"
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  runs {
    normal {
      min_query_count: 100
      min_duration: 60
      max_duration: 300
    }
    quick {
      min_query_count: 10
      min_duration: 10
      max_duration: 40
    }
    rapid {
      min_query_count: 6
      min_duration: 6
      max_duration: 60
    }
  }
  datasets {
    type: MMLU
      full {
      name: "TinyMMLU prompt set for LLM"
      input_path: "local:///mlperf_datasets/tinymmlu/data.tfrecord"
      input_checksum: "c20f9115582217af15e4d9955b41ace1"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    lite {
      name: "TinyMMLU prompt set for LLM"
      input_path: "local:///mlperf_datasets/tinymmlu/data.tfrecord"
      input_checksum: "c20f9115582217af15e4d9955b41ace1"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "TinyMMLU prompt set for LLM"
      input_path: "local:///mlperf_datasets/tinymmlu/data.tfrecord"
      input_checksum: "c20f9115582217af15e4d9955b41ace1"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
  }
  model {
    id: "LLM"
    name: "LLM"
  }
}

task {
  id: "stable_diffusion"
  name: "Stable Diffusion"
  max_throughput: 2000
  max_accuracy: 1.0
  scenario: "SingleStream"
  runs {
    normal {
      min_query_count: 1024
      min_duration: 60
      max_duration: 300
    }
    quick {
      min_query_count: 128
      min_duration: 10
      max_duration: 40
    }
    rapid {
      min_query_count: 64
      min_duration: 6
      max_duration: 60
    }
  }
  datasets {
    type: COCOGEN
    full {
      name: "COCO validation set for Stable Diffusion"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v4_1/coco_gen_test.tfrecord"
      input_checksum: "b564d2c228a867148fa7d6df415a0368"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v4_1/clip_model_512x512_openai-clip-vit-large-patch14.tflite"
      groundtruth_checksum: "39a07ffaea0806ee6148874ef228cc77"
    }
    lite {
      name: "COCO validation set for Stable Diffusion"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v4_1/coco_gen_full.tfrecord"
      input_checksum: "5cf967d2b2128edeb1b4d6eca6e8d94d"
      groundtruth_path: ""
      groundtruth_checksum: ""
    }
    tiny {
      name: "COCO validation set for Stable Diffusion"
      input_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v4_1/coco_gen_test.tfrecord"
      input_checksum: "b564d2c228a867148fa7d6df415a0368"
      groundtruth_path: "https://mobile.mlcommons-storage.org/app-resources/datasets/v4_1/clip_model_512x512_openai-clip-vit-large-patch14.tflite"
      groundtruth_checksum: "39a07ffaea0806ee6148874ef228cc77"
    }
  }
  model {
    id: "stable_diffusion"
    name: "StableDiffusion"
  }
  custom_config {
    id: "stable_diffusion_seed"
    value: "633994880"
  }
  custom_config {
    id: "stable_diffusion_num_steps"
    value: "20"
  }
}
