substitutions:
  # allow to override device selection in trigger description
  _DEVICE_SELECTOR: model=redfin,version=30,locale=en,orientation=portrait
  _DEVICE_SELECTOR_DESCRIPTION: redfin is Pixel 5e

steps:
  - id: pull-apks
    name: gcr.io/cloud-builders/gsutil
    timeout: 10s
    entrypoint: bash
    args:
      - -xc
      - |
        mkdir -p output
        gsutil cp -r gs://$_APK_LOCATION/$_APK_SUBFOLDER output
        mv output/$_APK_SUBFOLDER output/apks
  - id: firebase-instrumentation-test
    name: gcr.io/cloud-builders/gcloud
    waitFor:
      - pull-apks
    timeout: 1440s # 24 minutes
    entrypoint: bash
    args:
      - -xc
      - |
        gcloud firebase test android run \
          --type instrumentation \
          --app output/apks/$_APK_TEST_MAIN_NAME \
          --test output/apks/$_APK_TEST_HELPER_NAME \
          --timeout 20m \
          --device $_DEVICE_SELECTOR

timeout: 1500s # 25 minutes
