substitutions:
  # only a reference, overridden in GCP trigger settings
  _APK_LOCATION: gs://path/to/apks
  _APK_SUFFIX: t-123456
  # allow to optionally override device selection in trigger description
  _DEVICE_SELECTOR: model=redfin,version=30,locale=en,orientation=portrait
  # Just a human-friendly description, to make reading logs easier
  _DEVICE_SELECTOR_DESCRIPTION: redfin is Pixel 5e
  # optionally run test on more devices
  # make empty to skip additional device tests
  _DEVICE_SELECTOR2:
  _DEVICE_SELECTOR3:
  _DEVICE_SELECTOR4:

steps:
  - id: pull-apks
    name: gcr.io/cloud-builders/gsutil
    timeout: 60s
    entrypoint: bash
    args:
      - -xc
      - |
        mkdir -p output
        gsutil cp -r gs://$_APK_LOCATION output
        mv output/$$(basename $_APK_LOCATION) output/apks
  - id: firebase-instrumentation-test-1
    name: gcr.io/cloud-builders/gcloud
    waitFor:
      - pull-apks
    timeout: 1440s # 24 minutes
    entrypoint: bash
    args:
      - -xc
      - |
        DEVICE_ARG="--device $_DEVICE_SELECTOR"
        if [ ! -z "$_DEVICE_SELECTOR2" ]; then DEVICE_ARG="$$DEVICE_ARG --device $_DEVICE_SELECTOR2"; fi
        if [ ! -z "$_DEVICE_SELECTOR3" ]; then DEVICE_ARG="$$DEVICE_ARG --device $_DEVICE_SELECTOR3"; fi
        if [ ! -z "$_DEVICE_SELECTOR4" ]; then DEVICE_ARG="$$DEVICE_ARG --device $_DEVICE_SELECTOR4"; fi
        gcloud firebase test android run \
          --type instrumentation \
          --app output/apks/test-main-$_APK_SUFFIX.apk \
          --test output/apks/test-helper-$_APK_SUFFIX.apk \
          --timeout 20m \
          $$DEVICE_ARG

timeout: 1500s # 25 minutes
