substitutions:
  # only a reference, overridden in GCP trigger settings
  _APK_LOCATION: gs://path/to/apks
  _APK_SUFFIX: t-123456
  # allow to optionally override device selection in trigger description
  _DEVICE_SELECTOR: model=redfin,version=30,locale=en,orientation=portrait
  _DEVICE_SELECTOR_DESCRIPTION: redfin is Pixel 5e

steps:
  - id: pull-apks
    name: gcr.io/cloud-builders/gsutil
    timeout: 60s
    entrypoint: bash
    args:
      - -xc
      - |
        mkdir -p output
        gsutil cp -r gs://$_APK_LOCATION output
        mv output/$$(basename $_APK_LOCATION) output/apks
  - id: firebase-instrumentation-test
    name: gcr.io/cloud-builders/gcloud
    waitFor:
      - pull-apks
    timeout: 1440s # 24 minutes
    entrypoint: bash
    args:
      - -xc
      - |
        gcloud firebase test android run \
          --type instrumentation \
          --app output/apks/test-main-$_APK_SUFFIX \
          --test output/apks/test-helper-$_APK_SUFFIX \
          --timeout 20m \
          --device $_DEVICE_SELECTOR

timeout: 1500s # 25 minutes
