substitutions:
  _IMAGE_NAME: mlperf-mobile-flutter-android
# Building apks with flutter requires a lot of memory.
# Builds on standard machines with 4GB of RAM can unexpectedly hang.
# Also the build is mostly CPU-intensive, so using 8-core machines
# reduces build time up to 3 times.
options:
  # machineType: 'E2_HIGHCPU_8'

steps:
  - name: 'gcr.io/$PROJECT_ID/windows-builder'
    args:
    - --machineType=c2-standard-4
    - --image=windows-cloud/global/images/windows-server-2019-dc-for-containers-v20220414
    - --command=powershell.exe -file ./.github/cloudbuild/build.ps1
    - --diskType=pd-ssd

timeout: 18000s # 5 hours
