# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting


common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_1/tflite/mobilenet_edgetpu_224_1.0_float.tflite"
    model_checksum: "66bb4eba50987221608f8487ed405794"
  }
  delegate_selected: "CPU"
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    batch_size: 2
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_1/tflite/mobilenet_edgetpu_224_1.0_float.tflite"
    model_checksum: "66bb4eba50987221608f8487ed405794"
  }
  delegate_selected: "CPU"
}

benchmark_setting {
  benchmark_id: "image_classification_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_open/raw/main/vision/mobilenetV4/MobileNetV4-Conv-Large-int8-ptq.tflite"
    model_checksum: "590a7a88640a18d28b16b6f571cdfc93"
   }
   delegate_selected: "NNAPI"

  }
  delegate_selected: "CPU"
}

benchmark_setting {
  benchmark_id: "image_classification_offline_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    batch_size: 2
    model_path: "https://github.com/mlcommons/mobile_open/raw/main/vision/mobilenetV4/MobileNetV4-Conv-Large-int8-ptq.tflite"
    model_checksum: "590a7a88640a18d28b16b6f571cdfc93"
  }
  delegate_selected: "CPU"
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v1_0/tflite/mobiledet.tflite"
    model_checksum: "566ceb72a4c7c8926fe4ac8eededb5bf"
  }
  delegate_selected: "CPU"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v0_7/tflite/mobilebert_float_384_gpu.tflite"
    model_checksum: "36a953d07a8c6f2d3e05b22e87cec95b"
  }
  delegate_selected: "CPU"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_open/raw/main/vision/mosaic/models_and_checkpoints/R4/mobile_segmenter_r4_argmax_f32.tflite"
    model_checksum: "b3a5d3c2e5756431a471ed5211c344a9"
  }
  delegate_selected: "CPU"
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "CPU"
    accelerator_name: "cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/tflite/edsr_f32b5_fp32.tflite"
    model_checksum: "672240427c1f3dc33baf2facacd9631f"
  }
  delegate_selected: "CPU"
}
