# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

benchmark_setting {
  benchmark_id: "image_classification_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "Neuron"
    accelerator_name: "neuron-mdla"
    accelerator_desc: "MediaTek NN accelerator via the Neuron SDK"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0_1/mediatek/mt6993/MobileNetV4-Conv-Large-int8-ptq.dla"
      model_checksum: "9a45093025e2986eaa5c6e494cbce4bd"
    }
    custom_setting: {
      id: "disable_coherent"
      value: "false"
    }
  }
  delegate_choice: {
    delegate_name: "NNAPI"
    accelerator_name: "npu"
    accelerator_desc: "NPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v4_0/tflite/MobileNetV4-Conv-Large-int8-ptq.tflite"
      model_checksum: "590a7a88640a18d28b16b6f571cdfc93"
    }
  }
  delegate_choice: {
    delegate_name: "GPU"
    accelerator_name: "gpu"
    accelerator_desc: "GPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v4_0/tflite/MobileNetV4-Conv-Large-fp32.tflite"
      model_checksum: "b57cc2a027607c3b36873a15ace84acb"
    }
  }
  delegate_selected: "Neuron"
}

benchmark_setting {
  benchmark_id: "image_classification_offline_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "Neuron"
    accelerator_name: "neuron-mdla"
    accelerator_desc: "MediaTek NN accelerator via the Neuron SDK"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0_1/mediatek/mt6993/MobileNetV4-Conv-Large-int8-ptq_offline.dla"
      model_checksum: "5019f50e3654ee44b93fdf1b02a92d76"
    }
    custom_setting: {
      id: "thread_pool_size"
      value: "16"
    }
    custom_setting: {
      id: "exec_num"
      value: "4"
    }
    custom_setting: {
      id: "model_batch_size"
      value: "16"
    }
    custom_setting: {
      id: "disable_coherent"
      value: "true"
    }
    batch_size: 2458
  }
  delegate_choice: {
    delegate_name: "NNAPI"
    accelerator_name: "npu"
    accelerator_desc: "NPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v4_0/tflite/MobileNetV4-Conv-Large-int8-ptq.tflite"
      model_checksum: "590a7a88640a18d28b16b6f571cdfc93"
    }
  }
  delegate_choice: {
    delegate_name: "GPU"
    accelerator_name: "gpu"
    accelerator_desc: "GPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v4_0/tflite/MobileNetV4-Conv-Large-fp32.tflite"
      model_checksum: "b57cc2a027607c3b36873a15ace84acb"
    }
  }
  delegate_selected: "Neuron"
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "Neuron"
    accelerator_name: "neuron"
    accelerator_desc: "MediaTek NN accelerator via the Neuron SDK"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0_1/mediatek/mt6993/mobiledet_qat.dla"
      model_checksum: "bad523b0264ac739a9e0547377d14960"
    }
    custom_setting: {
      id: "disable_coherent"
      value: "false"
    }
  }
  delegate_choice: {
    delegate_name: "NNAPI"
    accelerator_name: "npu"
    accelerator_desc: "NPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v1_0/mobiledet_qat.tflite"
      model_checksum: "6c7af49d97a2b2488222d94936d2dc18"
    }
  }
  delegate_choice: {
    delegate_name: "GPU"
    accelerator_name: "gpu"
    accelerator_desc: "GPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v1_0/mobiledet.tflite"
      model_checksum: "566ceb72a4c7c8926fe4ac8eededb5bf"
    }
  }
  delegate_selected: "Neuron"
  single_stream_expected_latency_ns: 500000
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "Neuron"
    accelerator_name: "neuron-no-ahwb"
    accelerator_desc: "MediaTek NN accelerator + VPU via the Neuron SDK"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0_1/mediatek/mt6993/mobilebert_int8_384_nnapi.dla"
      model_checksum: "84ded5c021584ecbbd34c6382a96d716"
    }
    custom_setting: {
      id: "disable_coherent"
      value: "false"
    }
    batch_size: 1
  }
  delegate_choice: {
    delegate_name: "NNAPI"
    accelerator_name: "npu"
    accelerator_desc: "NPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v0_7/mobilebert_int8_384_nnapi.tflite"
      model_checksum: "3944a2dee04a5f8a5fd016ac34c4d390"
    }
  }
  delegate_choice: {
    delegate_name: "GPU"
    accelerator_name: "gpu"
    accelerator_desc: "GPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v0_7/mobilebert_float_384_gpu.tflite"
      model_checksum: "36a953d07a8c6f2d3e05b22e87cec95b"
    }
  }
  delegate_selected: "Neuron"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "Neuron"
    accelerator_name: "neuron"
    accelerator_desc: "NPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0_1/mediatek/mt6993/mobile_segmenter_r4_quant_argmax_uint8.dla"
      model_checksum: "8b5df25b167f3248dbfa7cd72547cebc"
    }
    custom_setting: {
      id: "disable_coherent"
      value: "false"
    }
  }
  delegate_choice: {
    delegate_name: "NNAPI"
    accelerator_name: "npu"
    accelerator_desc: "MediaTek NN accelerator via the Neuron SDK"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v2_0/mobile_segmenter_r4_quant_argmax_uint8.tflite"
      model_checksum: "b7a7620b8b818d64305b51ab796bfb1d"
    }
  }
  delegate_choice: {
    delegate_name: "GPU"
    accelerator_name: "gpu"
    accelerator_desc: "GPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v2_0/mobile_segmenter_r4_argmax_f32.tflite"
      model_checksum: "b3a5d3c2e5756431a471ed5211c344a9"
    }
  }
  delegate_selected: "Neuron"
  single_stream_expected_latency_ns: 300000
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "TFLite"
  delegate_choice: {
    delegate_name: "Neuron"
    accelerator_name: "neuron"
    accelerator_desc: "MediaTek NN accelerator via the Neuron SDK"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0_1/mediatek/mt6993/edsr_f32b5_full_qint8.dla"
      model_checksum: "104318678959015eef1748795385372a"
    }
    custom_setting: {
      id: "disable_coherent"
      value: "false"
    }
  }
  delegate_choice: {
    delegate_name: "NNAPI"
    accelerator_name: "npu"
    accelerator_desc: "NPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v3_0/edsr_f32b5_full_qint8.tflite"
      model_checksum: "18ce6df0e4603f4b4ee5d04193708d9c"
    }
  }
  delegate_choice: {
    delegate_name: "GPU"
    accelerator_name: "gpu"
    accelerator_desc: "GPU"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v3_0/edsr_f32b5_fp32.tflite"
      model_checksum: "672240427c1f3dc33baf2facacd9631f"
    }
  }
  delegate_selected: "Neuron"
}
