include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/localizations/**
    - lib/protos/**
  language:
    strict-casts: true

linter:
  # https://dart.dev/tools/linter-rules
  rules:
    avoid_print: false
    prefer_single_quotes: true
    prefer_function_declarations_over_variables: false
    always_use_package_imports: true
    unawaited_futures: true
    avoid_void_async: true
