include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - bazel-*/**
    - lib/localizations/**
    - lib/protos/**
  strong-mode:
    implicit-casts: false

linter:
  rules:
    avoid_print: false
