include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/localizations/**
    - lib/protos/**
  strong-mode:
    implicit-casts: false

linter:
  rules:
    avoid_print: false
    unawaited_futures: true
    prefer_single_quotes: true
