name: mlperfbench
description: The MLPerf app offers a simple mobile UI for executing MLPerf inference tasks and comparing results.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version format: <semantic_app_version>+<build_number>.
# Note: build_number will be set by CI using the CLI option --build-number
version: 6.0.0+1

environment:
  sdk: ^3.12.0  # Dart SDK version
  flutter: ^3.44.0  # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^13.2.0
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  quiver: ^3.2.1
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  wakelock_plus: ^1.2.8
  uuid: ^4.4.0
  package_info_plus: ^10.2.0
  device_marketing_names: ^2.0.2
  share_plus: ^13.2.0
  crypto: ^3.0.3
  tuple: ^2.0.2
  bot_toast: ^4.1.3
  process_run: ^1.3.4
  worker_manager: ^7.0.2
  ffi: ^2.1.2
  async: ^2.11.0
  archive: ^4.0.9
  http: ^1.2.1
  json_annotation: ^4.12.0
  flutter_markdown: ^0.7.1
  firebase_core: ^4.11.0
  firebase_storage: ^13.4.3
  firebase_auth: ^6.5.4
  firebase_ui_auth: ^3.0.1
  firebase_crashlytics: ^5.2.4
  firebase_app_check: ^0.4.5
  upgrader: ^13.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  import_sorter: ^4.6.0
  flutter_lints: ^6.0.0
  protoc_plugin: ^25.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0

flutter_launcher_icons:
  image_path: "assets/ic_launcher_ios.png"
  ios: true
  android: "ic_launcher"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/ic_launcher_ios.png"
    icon_size: 256

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/text/
    - assets/android-boards/database.json
  generate: true
  uses-material-design: true
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

import_sorter:
  comments: false
  ignored_files:
    - \/.pub-cache\/*
    - \/lib/protos\/*
    - \/lib/localizations/*
