workspace(name = "mlperf_app")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_protobuf",
    sha256 = "9b4ee22c250fe31b16f1a24d61467e40780a3fbb9b91c3b65be2a376ed913a1a",
    strip_prefix = "protobuf-3.13.0",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.13.0.tar.gz"],
)

http_archive(
    name = "org_tensorflow",
    patch_args = ["-p1"],
    patches = [
        # Fix tensorflow not being able to read image files on Windows
        "//:third_party/tensorflow-fix-file-opening-mode-for-Windows.patch",
    ],
    sha256 = "40d3203ab5f246d83bae328288a24209a2b85794f1b3e2cd0329458d8e7c1985",
    strip_prefix = "tensorflow-2.6.0",
    urls = [
        "https://github.com/tensorflow/tensorflow/archive/v2.6.0.zip",
    ],
)

# Initialize tensorflow workspace.
load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")

tf_workspace3()

load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")

tf_workspace2()

# Android.
android_sdk_repository(
    name = "androidsdk",
    api_level = 29,
)

android_ndk_repository(
    name = "androidndk",
)

http_archive(
    name = "org_mlperf_inference",
    build_file = "@//third_party:loadgen.BUILD",
    patch_cmds = [
        "python3 loadgen/version_generator.py loadgen/version_generated.cc loadgen",
    ],
    sha256 = "f4c57a3f3cd71f2dac166a79ad760b824aafda7b91400889acff4a9c7dbdaf8e",
    strip_prefix = "inference-a77ac37d07145d9f3123465a8fd18f9ebbde5d6a",
    urls = [
        "https://github.com/mlcommons/inference/archive/a77ac37d07145d9f3123465a8fd18f9ebbde5d6a.tar.gz",
    ],
)

http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "9f9eb6cdd25d7932cb939df24807c2d70772aad7a79f1357e25ced9d0d443cfd",
    strip_prefix = "rules_apple-0.19.0",
    urls = [
        "https://github.com/bazelbuild/rules_apple/archive/refs/tags/0.19.0.zip",
    ],
)

http_archive(
    name = "build_bazel_rules_swift",
    sha256 = "ef728d0d99276d62b2393c350f29f176a6f38a925f2d12c37c4ed64f6906c2f5",
    strip_prefix = "rules_swift-0.13.0",
    urls = [
        "https://github.com/bazelbuild/rules_swift/archive/refs/tags/0.13.0.zip",
    ],
)

http_archive(
    name = "build_bazel_apple_support",
    sha256 = "249be3d90bc4211928a5260c4bc5792a236c58d1b6183c0e30f58db8710fc952",
    strip_prefix = "apple_support-0.7.2",
    urls = [
        "https://github.com/bazelbuild/apple_support/archive/refs/tags/0.7.2.zip",
    ],
)
