// File originally generated by FlutterFire CLI.
// Then modified and used as template for our use case.
// See docs/environment-setup/env-setup-firebase.md for more info how to use your own Firebase project.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static bool available() {
    try {
      final currentPlatform = DefaultFirebaseOptions.currentPlatform;
      return currentPlatform.apiKey.isNotEmpty &&
          currentPlatform.appId.isNotEmpty &&
          currentPlatform.projectId.isNotEmpty;
    } catch (e) {
      return false;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_ANDROID_API_KEY',
    appId: 'FIREBASE_ANDROID_APP_ID',
    // common
    projectId: 'FIREBASE_PROJECT_ID',
    messagingSenderId: 'FIREBASE_MESSAGING_SENDER_ID',
    databaseURL: 'FIREBASE_DATABASE_URL',
    storageBucket: 'FIREBASE_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_IOS_API_KEY',
    appId: 'FIREBASE_IOS_APP_ID',
    iosClientId: 'FIREBASE_IOS_CLIENT_ID',
    iosBundleId: 'FIREBASE_IOS_BUNDLE_ID',
    // common
    projectId: 'FIREBASE_PROJECT_ID',
    messagingSenderId: 'FIREBASE_MESSAGING_SENDER_ID',
    databaseURL: 'FIREBASE_DATABASE_URL',
    storageBucket: 'FIREBASE_STORAGE_BUCKET',
  );

  static const ciUserEmail = 'FIREBASE_CI_USER_EMAIL';
  static const ciUserPassword = 'FIREBASE_CI_USER_PASSWORD';
}
