# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "NPU"
    custom_setting {
      id: "preset"
      value: "1001"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "true"
    }
    custom_setting {
      id: "lazy_mode"
      value: "false"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v2_0/Samsung/ic_single.nnc"
    model_checksum: "a49175f3f4f37f59780995cec540dbf2"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 900000
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "NPU"
    custom_setting {
      id: "preset"
      value: "1004"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Uint8"
    }
    custom_setting {
      id: "extension"
      value: "false"
    }
    custom_setting {
      id: "lazy_mode"
      value: "false"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v2_0/Samsung/sm_uint8.nnc"
    model_checksum: "f715f55818863f371336ad29ecba1183"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "NPU"
    custom_setting {
      id: "preset"
      value: "1003"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "true"
    }
    custom_setting {
      id: "lazy_mode"
      value: "false"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v2_0/Samsung/od.nnc"
    model_checksum: "6b34201b6696fa75311d0d43820e03d2"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "gpu"
    accelerator_desc: "gpu"
    custom_setting {
      id: "preset"
      value: "1000"
    }
    custom_setting {
      id: "i_type"
      value: "Int32"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "false"
    }
    custom_setting {
      id: "lazy_mode"
      value: "false"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v2_0/Samsung/mobile_bert_gpu.nnc"
    model_checksum: "d98dfcc37ad33fa7081d6fbb5bc6ddd1"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "npu"
    batch_size: 8192
    custom_setting {
      id: "scenario"
      value: "offline"
    }
    custom_setting {
      id: "preset"
      value: "1002"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "false"
    }
    custom_setting {
      id: "lazy_mode"
      value: "false"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v2_0/Samsung/ic_offline.nnc"
    model_checksum: "8832370c770fa820dfde83e039e3243c"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}
