# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "NPU"
    custom_setting {
      id: "preset"
      value: "1005"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "true"
    }
    custom_setting {
      id: "lazy_mode"
      value: "true"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/samsung/ic.nnc"
    model_checksum: "1756e790704bea5be37431877a196ea1"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 200000
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "NPU"
    custom_setting {
      id: "preset"
      value: "1005"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Uint8"
    }
    custom_setting {
      id: "extension"
      value: "true"
    }
    custom_setting {
      id: "lazy_mode"
      value: "true"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/samsung/sm_uint8.nnc"
    model_checksum: "c58979294a01c1a8b7306cbf213ffd42"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 500000
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "NPU"
    custom_setting {
      id: "preset"
      value: "1005"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "true"
    }
    custom_setting {
      id: "lazy_mode"
      value: "true"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/samsung/od.nnc"
    model_checksum: "6ec9c58af2b1cd772fb45ac51db07c31"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 450000
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "NPU"
    custom_setting {
      id: "preset"
      value: "1005"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Int8"
    }
    custom_setting {
      id: "extension"
      value: "true"
    }
    custom_setting {
      id: "lazy_mode"
      value: "true"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/samsung/sr.nnc"
    model_checksum: "2542bd74108b286822fcd1fc4b8bc316"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 990000
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "npu"
    accelerator_desc: "npu"
    custom_setting {
      id: "preset"
      value: "1005"
    }
    custom_setting {
      id: "i_type"
      value: "Int32"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "true"
    }
    custom_setting {
      id: "lazy_mode"
      value: "true"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/samsung/mobile_bert.nnc"
    model_checksum: "82dee62592db68a095396da3caacf67b"
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 990000
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "samsung_npu"
    accelerator_desc: "npu"
    batch_size: 6144
    custom_setting {
      id: "scenario"
      value: "offline"
    }
    custom_setting {
      id: "preset"
      value: "1003"
    }
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    custom_setting {
      id: "extension"
      value: "false"
    }
    custom_setting {
      id: "lazy_mode"
      value: "false"
    }
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_1/samsung/ic_offline.nnc"
    model_checksum: "0c4c08850eb790dcaa7c77cc352dbfc1"
  }
  delegate_selected: "ENN_NPU"

  single_stream_expected_latency_ns: 140000
}
