# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "npu"
    accelerator_desc: "npu"
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v1_0/ic.nnc"
      model_checksum: "955ef2ac3c134820eab901f3dac9f732"
    }
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 900000
}

benchmark_setting {
  benchmark_id: "image_segmentation_v1"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "npu"
    accelerator_desc: "npu"
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Uint8"
    }
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v1_0/is.nnc"
      model_checksum: "b501ed669da753b08a151639798af37e"
    }
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "npu"
    accelerator_desc: "npu"
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Uint8"
    }
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v1_0/sm_uint8.nnc"
      model_checksum: "483eee2df253ecc135a6e8701cc0c909"
    }
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "npu"
    accelerator_desc: "npu"
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v1_0/od.nnc"
      model_checksum: "a3c7b5e8d6b978c05807e8926584758c"
    }
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "gpu"
    accelerator_desc: "gpu"
    custom_setting {
      id: "i_type"
      value: "Int32"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v1_0/lu.nnc"
      model_checksum: "215ee3b9224d15dc50b30d56fa7b7396"
    }
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "ENN"
  delegate_choice: {
    delegate_name: "ENN_NPU"
    accelerator_name: "npudsp"
    accelerator_desc: "npu"
    batch_size: 8192
    custom_setting {
      id: "i_type"
      value: "Uint8"
    }
    custom_setting {
      id: "o_type"
      value: "Float32"
    }
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v1_0/ic_offline.nncgo"
      model_checksum: "c38acf6c66ca32c525c14ce25ead823a"
    }
  }
  delegate_selected: "ENN_NPU"
  single_stream_expected_latency_ns: 1000000
}
