# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

common_setting {
  id: "profiling_level"
  name: "profile level"
  value {
    value: "off"
    name: "profile level"
  }
}

benchmark_setting {
  benchmark_id: "image_classification_v2"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "uint_8"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_file: {
      model_path: "local:///mlperf_models/mobilenet_v4_htp.dlc"
      model_checksum: ""
    }
  }
  single_stream_expected_latency_ns: 250000
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_classification_offline_v2"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "uint_8"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "psnpe_dsp"
    accelerator_desc: "HTP"
    batch_size: 12288
    model_file: {
      model_path: "local:///mlperf_models/mobilenet_v4_htp_batched_4.dlc"
      model_checksum: ""
    }
  }
  delegate_selected: "SNPE_DSP"
}


benchmark_setting {
  benchmark_id: "object_detection"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_tensors"
    value: "Postprocessor/BatchMultiClassNonMaxSuppression_classes,Postprocessor/BatchMultiClassNonMaxSuppression_num_detections,detection_scores:0,detection_boxes:0"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_file: {
      model_path: "local:///mlperf_models/ssd_mobiledet_qat_htp.dlc"
      model_checksum: ""
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_tensors"
    value: "transpose:0"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "float_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_file: {
      model_path: "local:///mlperf_models/mobilebert_quantized_htp.dlc"
      model_checksum: ""
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "SNPE"
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "int_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_file: {
      model_path: "local:///mlperf_models/mobile_mosaic_htp.dlc"
      model_checksum: ""
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_file: {
      model_path: "local:///mlperf_models//snusr_htp.dlc"
      model_checksum: ""
    }
  }
  delegate_selected: "SNPE_DSP"
}
