# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

common_setting {
  id: "profiling_level"
  name: "profile level"
  value {
    value: "off"
    name: "profile level"
  }
}

benchmark_setting {
  benchmark_id: "image_classification_v2"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v5_0/qualcomm/mobilenet_v4_htp.dlc"
      model_checksum: "4dc06ff76d00a442be24b796651a27df"
    }
  }
  single_stream_expected_latency_ns: 500000
  delegate_selected: "SNPE_GPU_FP16"
}

benchmark_setting {
  benchmark_id: "image_classification_offline_v2"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "psnpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    batch_size: 12360
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v5_0/qualcomm/mobilenet_v4_htp_batched_4.dlc"
      model_checksum: "07d1d4f86d09e950434bc0c790d8b00a"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_tensors"
    value: "transpose:0"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "float_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "sustained_high_performance"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v5_0/qualcomm/mobilebert_quantized_htp.dlc"
      model_checksum: "4cfaced53aed0ea563628d626bf2570b"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "SNPE"
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "int_32"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v5_0/qualcomm/mobile_mosaic_htp.dlc"
      model_checksum: "b2b2a51ae3a52d97b1eb44c00432b713"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}
benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v5_0/qualcomm/snusr_htp.dlc"
      model_checksum: "8ff44a39cf911b3fd04809f4967d1501"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}
