# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

common_setting {
  id: "profiling_level"
  name: "profile level"
  value {
    value: "off"
    name: "profile level"
  }
}

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    custom_setting {
      id: "cpu_int8"
      value: "true"
    }
    delegate_name: "SNPE_CPU"
    accelerator_name: "snpe_cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobilenet_edgetpu_224_1.0_htp.dlc"
    model_checksum: "02ae4e1770b52431fb1bf915ded297a1"
  }
  delegate_selected: "SNPE_CPU"
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    custom_setting {
      id: "cpu_int8"
      value: "true"
    }
    delegate_name: "SNPE_CPU"
    accelerator_name: "psnpe_cpu"
    accelerator_desc: "CPU"
    batch_size: 12288
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobilenet_edgetpu_224_1.0_htp_batched_3.dlc"
    model_checksum: "0f4fa8d6ba0a3c73753de1be63f5da4a"
  }
  delegate_selected: "SNPE_CPU"
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_layers"
    value: "Postprocessor/BatchMultiClassNonMaxSuppression"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "cpu_int8"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_CPU"
    accelerator_name: "snpe_cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/ssd_mobiledet_qat_htp.dlc"
    model_checksum: "d26a1c78335f2c71d9aa85cb8b07c8c9"
  }
  delegate_selected: "SNPE_CPU"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_layers"
    value: "transpose"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "float_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    custom_setting {
      id: "cpu_int8"
      value: "true"
    }
    delegate_name: "SNPE_CPU"
    accelerator_name: "snpe_cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobilebert_quantized_htp.dlc"
    model_checksum: "8d2452fdc593c6cdaf6a63ac087522ca"
  }
  delegate_selected: "SNPE_CPU"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "SNPE"
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "int_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_CPU"
    accelerator_name: "snpe_cpu"
    accelerator_desc: "CPU"
    custom_setting {
      id: "cpu_int8"
      value: "true"
    }
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobile_mosaic_htp.dlc"
    model_checksum: "1d840d4b944e8ed2228007e8003b4c64"
  }
  delegate_selected: "SNPE_CPU"
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    custom_setting {
      id: "cpu_int8"
      value: "true"
    }
    delegate_name: "SNPE_CPU"
    accelerator_name: "snpe_cpu"
    accelerator_desc: "CPU"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/snusr_htp.dlc"
    model_checksum: "005727e2f54c28e256eff0402daa8cbc"
  }
  delegate_selected: "SNPE_CPU"
}
