# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

common_setting {
  id: "profiling_level"
  name: "profile level"
  value {
    value: "off"
    name: "profile level"
  }
}

benchmark_setting {
  benchmark_id: "image_classification_v2"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0/qualcomm/mobilenet_v4_htp.dlc"
      model_checksum: "9bf2200ae028dcf17041f530371c7b26"
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_classification_offline_v2"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "psnpe_dsp"
    accelerator_desc: "HTP"
    batch_size: 12288
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0/qualcomm/mobilenet_v4_htp_batched_4.dlc"
      model_checksum: "c0f665a63bac7dcb2f592403894ddfed"
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_tensors"
    value: "Postprocessor/BatchMultiClassNonMaxSuppression_classes,Postprocessor/BatchMultiClassNonMaxSuppression_num_detections,detection_scores:0,detection_boxes:0"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0/qualcomm/ssd_mobiledet_qat_htp.dlc"
      model_checksum: "ef219d5e618f933486ee107393b0bccd"
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_tensors"
    value: "transpose:0"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "float_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0/qualcomm/mobilebert_quantized_htp.dlc"
      model_checksum: "2a1e282552998aec941bb560dd2b7e6c"
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "SNPE"
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "int_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0/qualcomm/mobile_mosaic_htp.dlc"
      model_checksum: "8604d60708eb21e6b1d4024b10b52d19"
    }
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "true"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/models/v6_0/qualcomm/snusr_htp.dlc"
      model_checksum: "bf3e54f70b770668494ab02ead11b1df"
    }
  }
  delegate_selected: "SNPE_DSP"
}
