# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

common_setting {
  id: "profiling_level"
  name: "profile level"
  value {
    value: "off"
    name: "profile level"
  }
}

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.0-snpe/mobilenet_edgetpu_224_1.0_htp.dlc"
    model_checksum: "2e7c4d33b480b5566bdf05e1204b6152"
  }
  single_stream_expected_latency_ns: 500000
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "psnpe_dsp"
    accelerator_desc: "HTP"
    batch_size: 12288
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.0-snpe/mobilenet_edgetpu_224_1.0_htp_batched_sd8g2.dlc"
    model_checksum: "78a54fc8913d4fa654dcd41a26850c1e"
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_layers"
    value: "Postprocessor/BatchMultiClassNonMaxSuppression"
  }
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.0-snpe/ssd_mobiledet_qat_htp.dlc"
    model_checksum: "65937d5b58414d86fc42872945e2f5cf"
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_layers"
    value: "transpose"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "float_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "sustained_high_performance"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.0-snpe/mobilebert_quantized_htp.dlc"
    model_checksum: "6dc1f1a47a764381b00c8423b07caac1"
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "SNPE"
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "int_32"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.0-snpe/mobile_mosaic_htp.dlc"
    model_checksum: "e921828320d251a5f7160952bbd750ec"
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.0-snpe/snusr_htp.dlc"
    model_checksum: "3dc4b1e7ae23620704d76b56f88527d0"
  }
  delegate_selected: "SNPE_DSP"
}
