# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

common_setting {
  id: "profiling_level"
  name: "profile level"
  value {
    value: "off"
    name: "profile level"
  }
}

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v4_0/qualcomm/mobilenet_edgetpu_224_1.0_htp.dlc"
      model_checksum: "cdf1fe622b309f692e05781661248a2b"
    }
  }
  single_stream_expected_latency_ns: 500000
  delegate_selected: "SNPE_GPU_FP16"
}

benchmark_setting {
  benchmark_id: "image_classification_v2"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v4_0/qualcomm/mobilenet_v4_htp.dlc"
      model_checksum: "dbab3e231e5f83aabc80d5b69e6dad32"
    }
  }
  single_stream_expected_latency_ns: 500000
  delegate_selected: "SNPE_GPU_FP16"
}
benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "psnpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    batch_size: 12288
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v4_0/qualcomm/mobilenet_edgetpu_224_1.0_htp_batched_4.dlc"
      model_checksum: "6523060565b8d3f326f3f323c531fc1c"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}
benchmark_setting {
  benchmark_id: "image_classification_offline_v2"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "psnpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    batch_size: 12360
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v4_0/qualcomm/mobilenet_v4_htp_batched_4.dlc"
      model_checksum: "0de3b75022ce5c27d5902a080ec1cea0"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}
benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_layers"
    value: "transpose"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "float_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "sustained_high_performance"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v4_0/qualcomm/mobilebert_quantized_htp.dlc"
      model_checksum: "7a641e4df84fc06a1237b7fe1b1c5b08"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}
benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "SNPE"
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "int_32"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v4_0/qualcomm/mobile_mosaic_htp.dlc"
      model_checksum: "e870526444c1e48df4f0505e530ecfdf"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}
benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "false"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  custom_setting {
    id: "perf_profile"
    value: "burst"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_GPU_FP16"
    accelerator_name: "snpe_gpu_fp16"
    accelerator_desc: "GPU_FP16"
    model_file: {
      model_path: "https://mobile.mlcommons-storage.org/app-resources/v4_0/qualcomm/snusr_htp.dlc"
      model_checksum: "84ef0d9c2e7b710381cea962a22a0b41"
    }
  }
  delegate_selected: "SNPE_GPU_FP16"
}