# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

common_setting {
  id: "num_threads"
  name: "Number of threads"
  value {
    value: "4"
    name: "4 threads"
  }
}

common_setting {
  id: "profiling_level"
  name: "profile level"
  value {
    value: "off"
    name: "profile level"
  }
}

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobilenet_edgetpu_224_1.0_htp.dlc"
    model_checksum: ""
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "SNPE"
  custom_setting {
    id: "scenario"
    value: "Offline"
  }
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "psnpe_dsp"
    accelerator_desc: "HTP"
    batch_size: 12288
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobilenet_edgetpu_224_1.0_htp_batched_8.dlc"
    model_checksum: ""
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_layers"
    value: "Postprocessor/BatchMultiClassNonMaxSuppression"
  }
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "HTP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/ssd_mobiledet_qat_htp.dlc"
    model_checksum: ""
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "SNPE"
  custom_setting {
    id: "snpe_output_layers"
    value: "transpose"
  }
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  custom_setting {
    id: "input_buffer_type"
    value: "float_32"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobilebert_quantized_htp.dlc"
    model_checksum: ""
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "SNPE"
  custom_setting {
    id: "input_buffer_type"
    value: "uint_8"
  }
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  custom_setting {
    id: "output_buffer_type"
    value: "int_32"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe/mobile_mosaic_htp.dlc"
    model_checksum: ""
  }
  delegate_selected: "SNPE_DSP"
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "SNPE"
  custom_setting {
    id: "bg_load"
    value: "true"
  }
  custom_setting {
    id: "use_ion_buffer"
    value: "false"
  }
  delegate_choice: {
    priority: 1
    delegate_name: "SNPE_DSP"
    accelerator_name: "snpe_dsp"
    accelerator_desc: "DSP"
    model_path: "https://github.com/mlcommons/mobile_models/releases/download/v3.1-snpe//snusr_htp.dlc"
    model_checksum: ""
  }
  delegate_selected: "SNPE_DSP"
}
