package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "tflitebackend",
    srcs = ["//mobile_back_tflite/cpp/backend_tflite:libtflitebackend.so"],
)

cc_library(
    name = "tfliteneuronbackend",
    srcs = ["//mobile_back_tflite/cpp/backend_tflite:libtfliteneuronbackend.so"],
)
