package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "coremlbackend",
    srcs = ["//mobile_back_apple/cpp/backend_coreml:libcoremlbackend.so"],
)
