# proto-file: flutter/cpp/proto/backend_setting.proto
# proto-message: BackendSetting

benchmark_setting {
  benchmark_id: "image_classification"
  framework: "Core ML"
  delegate_choice: {
    delegate_name: "All"
    accelerator_name: "all"
    accelerator_desc: "All compute units"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel"
    model_checksum: "39483b20b878d46144ab4cfe9a3e5600"
  }
  delegate_choice: {
    delegate_name: "CPU & GPU"
    accelerator_name: "cpu&gpu"
    accelerator_desc: "CPU and GPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel"
    model_checksum: "39483b20b878d46144ab4cfe9a3e5600"
  }
   delegate_choice: {
    delegate_name: "CPU & NE"
    accelerator_name: "cpu&ne"
    accelerator_desc: "CPU and Neural Engine"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel"
    model_checksum: "39483b20b878d46144ab4cfe9a3e5600"
  }
  delegate_selected: "All"
}

benchmark_setting {
  benchmark_id: "image_classification_offline"
  framework: "Core ML"
  delegate_choice: {
    delegate_name: "All"
    accelerator_name: "all"
    accelerator_desc: "All compute units"
    batch_size: 32
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel"
    model_checksum: "39483b20b878d46144ab4cfe9a3e5600"
  }
  delegate_choice: {
    delegate_name: "CPU & GPU"
    accelerator_name: "cpu&gpu"
    accelerator_desc: "CPU and GPU"
    batch_size: 32
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel"
    model_checksum: "39483b20b878d46144ab4cfe9a3e5600"
  }
   delegate_choice: {
    delegate_name: "CPU & NE"
    accelerator_name: "cpu&ne"
    accelerator_desc: "CPU and Neural Engine"
    batch_size: 32
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobilenetEdgeTPU.mlmodel"
    model_checksum: "39483b20b878d46144ab4cfe9a3e5600"
  }
  delegate_selected: "All"
}

benchmark_setting {
  benchmark_id: "object_detection"
  framework: "Core ML"
  delegate_choice: {
    delegate_name: "All"
    accelerator_name: "all"
    accelerator_desc: "All compute units"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobileDet.mlmodel"
    model_checksum: "ef849fbf2132e205158f05ca42db25f4"
  }
  delegate_choice: {
    delegate_name: "CPU & GPU"
    accelerator_name: "cpu&gpu"
    accelerator_desc: "CPU and GPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobileDet.mlmodel"
    model_checksum: "ef849fbf2132e205158f05ca42db25f4"
  }
   delegate_choice: {
    delegate_name: "CPU & NE"
    accelerator_name: "cpu&ne"
    accelerator_desc: "CPU and Neural Engine"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobileDet.mlmodel"
    model_checksum: "ef849fbf2132e205158f05ca42db25f4"
  }
  delegate_selected: "All"
}

benchmark_setting {
  benchmark_id: "natural_language_processing"
  framework: "Core ML"
  delegate_choice: {
    delegate_name: "All"
    accelerator_name: "all"
    accelerator_desc: "All compute units"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobileBERT.mlmodel"
    model_checksum: "c7d544b5b3bd6cd9df7ebe8f04ecb7f9"
  }
  delegate_choice: {
    delegate_name: "CPU & GPU"
    accelerator_name: "cpu&gpu"
    accelerator_desc: "CPU and GPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobileBERT.mlmodel"
    model_checksum: "c7d544b5b3bd6cd9df7ebe8f04ecb7f9"
  }
   delegate_choice: {
    delegate_name: "CPU & NE"
    accelerator_name: "cpu&ne"
    accelerator_desc: "CPU and Neural Engine"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/MobileBERT.mlmodel"
    model_checksum: "c7d544b5b3bd6cd9df7ebe8f04ecb7f9"
  }
  delegate_selected: "All"
}

benchmark_setting {
  benchmark_id: "image_segmentation_v2"
  framework: "Core ML"
  delegate_choice: {
    delegate_name: "All"
    accelerator_name: "all"
    accelerator_desc: "All compute units"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/Mosaic.mlmodel"
    model_checksum: "362d6b5bb1b8e10ae5b4e223f60d4d10"
  }
  delegate_choice: {
    delegate_name: "CPU & GPU"
    accelerator_name: "cpu&gpu"
    accelerator_desc: "CPU and GPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/Mosaic.mlmodel"
    model_checksum: "362d6b5bb1b8e10ae5b4e223f60d4d10"
  }
   delegate_choice: {
    delegate_name: "CPU & NE"
    accelerator_name: "cpu&ne"
    accelerator_desc: "CPU and Neural Engine"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/Mosaic.mlmodel"
    model_checksum: "362d6b5bb1b8e10ae5b4e223f60d4d10"
  }
  delegate_selected: "All"
}

benchmark_setting {
  benchmark_id: "super_resolution"
  framework: "Core ML"
  delegate_choice: {
    delegate_name: "All"
    accelerator_name: "all"
    accelerator_desc: "All compute units"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/edsr_f32b5_fp32.mlmodel"
    model_checksum: "62489706f20b0c2ae561fb2204eefb61"
  }
  delegate_choice: {
    delegate_name: "CPU & GPU"
    accelerator_name: "cpu&gpu"
    accelerator_desc: "CPU and GPU"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/edsr_f32b5_fp32.mlmodel"
    model_checksum: "62489706f20b0c2ae561fb2204eefb61"
  }
   delegate_choice: {
    delegate_name: "CPU & NE"
    accelerator_name: "cpu&ne"
    accelerator_desc: "CPU and Neural Engine"
    model_path: "https://github.com/mlcommons/mobile_models/raw/main/v3_0/CoreML/edsr_f32b5_fp32.mlmodel"
    model_checksum: "62489706f20b0c2ae561fb2204eefb61"
  }
  delegate_selected: "All"
}