package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "litertbackend",
    srcs = ["//mobile_back_litert/cpp/backend_litert:liblitertbackend.so"],
)

cc_library(
    name = "litertbackenddll",
    srcs = ["//mobile_back_litert/cpp/backend_litert:liblitertbackend.dll"],
)
