package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "tflitepixelbackend",
    srcs = ["//mobile_back_pixel/cpp/backend_tflite:libtflitepixelbackend.so"],
)
