name: Android Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flutter:
    name: Run Flutter Android unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.3.5'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Create ephemeral files
        run: |
          flutter config --no-analytics &&
          dart pub global activate protoc_plugin &&
          export PATH="$PATH:$HOME/.pub-cache/bin" &&
          make flutter/prepare
      - name: Run Flutter tests
        run: make flutter/test/unit
