name: Android Test

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build or run number'
        required: true
        type: number

jobs:
  test-android-apk-unfied:
    runs-on: ubuntu-22.04
    env:
      MAIN_APK_NAME: test-main-unified-${{ inputs.build_number }}.apk
      HELPER_APK_NAME: test-helper-unified-${{ inputs.build_number }}.apk
    steps:
      - uses: actions/checkout@v4
      - name: Set up authentication for Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_MOBILE_APP_BUILD }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
      - name: Download test APK
        run: |
          gsutil cp $GCLOUD_BUCKET_PATH/test-main-unified.apk /tmp/$MAIN_APK_NAME
          gsutil cp $GCLOUD_BUCKET_PATH/test-helper-unified.apk /tmp/$HELPER_APK_NAME
      - name: Upload main app
        run: |
          curl -u "${{ secrets.BROWSERSTACK_CREDENTIALS }}" \
          -X POST "https://api-cloud.browserstack.com/app-automate/flutter-integration-tests/v2/android/app" \
          -F "file=@/tmp/$MAIN_APK_NAME" \
          -F "custom_id=$MAIN_APK_NAME"
      - name: Upload test suite
        run: |
          curl -u "${{ secrets.BROWSERSTACK_CREDENTIALS }}" \
          -X POST "https://api-cloud.browserstack.com/app-automate/flutter-integration-tests/v2/android/test-suite" \
          -F "file=@/tmp/$HELPER_APK_NAME" \
          -F "custom_id=$HELPER_APK_NAME"
      - name: Trigger App Automate
        env:
          BROWSERSTACK_CREDENTIALS: ${{ secrets.BROWSERSTACK_CREDENTIALS }}
          BROWSERSTACK_APP: ${{ env.MAIN_APK_NAME }}
          BROWSERSTACK_TEST_SUITE: ${{ env.HELPER_APK_NAME }}
          BROWSERSTACK_BUILD_TAG: ${{ inputs.build_number }}
          BROWSERSTACK_DEVICES: '["Samsung Galaxy S24-14.0", "Samsung Galaxy S24 Ultra-14.0", "Google Pixel 9 Pro-15.0"]'
        run: |
          bash .github/workflows/scripts/browserstack-app-automate.sh
