name: Code Analysis

on:
  push:
    branches: [ master, submission-v* ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonar:
    name: SonarScanner
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_IMAGE_TAG: ghcr.io/mlcommons/mobile_app_open-scanner:${{ github.run_number }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_OUT_DIR: sonar_build_wrapper_output
      REPO_NAME: ${{ github.event.repository.name }}
      PR_NUMBER: ${{ github.event.number }}
      PR_BRANCH: ${{ github.HEAD_REF }}
      PR_BASE: ${{ github.BASE_REF }}
      CONNECT_TTY_TO_DOCKER: 0
      WITH_TFLITE: 1
      WITH_PIXEL: 1
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin, javascript-typescript, python, actions
          build-mode: none
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
