name: 'Format: Java'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Java format check
        uses: axel-op/googlejavaformat-action@v3
        with:
          version: 1.9
          args: --set-exit-if-changed --replace
