name: 'Format: Buildifier +linter'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
      - name: Setup Go lang
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Set go env
        run: echo GOPATH=$GITHUB_WORKSPACE >> $GITHUB_ENV
      - name: Get buildifier
        run: go get github.com/bazelbuild/buildtools/buildifier
      - name: Run buildifier format check
        run: $GOPATH/bin/buildifier -mode=check -r ${{ github.workspace }}/src/github.com/${{ github.repository }}
      - name: Run buildifier linter
        run: $GOPATH/bin/buildifier -lint=warn -r ${{ github.workspace }}/src/github.com/${{ github.repository }}
