name: 'Format: misc. checks'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check prohibited extensions
        run: make lint/prohibited
      - name: Check large files
        run: make lint/big-files
      - name: Install dos2unix
        run: sudo apt-get install dos2unix
      - name: Check line endings
        run: make lint/line-endings
