name: iOS Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build and test iOS app
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12
    timeout-minutes: 120
    env:
      PERF_TEST: true
      WITH_APPLE: 1
      WITH_TFLITE: 0
      WITH_PIXEL: 0
      WITH_MEDIATEK: 0
      WITH_QTI: 0
      WITH_SAMSUNG: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Xcode DerivedData
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived_data-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-derived_data-
      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/flutter/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-
      - name: Cache bazel
        uses: actions/cache@v3
        with:
          path: /tmp/bazel_cache
          key: ${{ runner.os }}-bazel_cache-${{ hashFiles('**/BUILD', '**/WORKSPACE') }}
          restore-keys: ${{ runner.os }}-bazel_cache-
      - name: Build iOS app
        env:
          BAZEL_OUTPUT_ROOT_ARG: "--output_user_root=/tmp/bazel_output"
          BAZEL_CACHE_ARG: "--disk_cache=/tmp/bazel_cache"
        run: |
          cd flutter/ios/ci_scripts/ && bash ci_post_clone.sh
      - name: Run iOS tests
        run: |
          open -a Simulator && make flutter/test
