name: Unit tests

on:
  push:
    branches: [ master, submission-v* ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  merge_group:
    types: [ checks_requested ]

jobs:
  flutter:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'
          flutter-version: '3.19.6'
      - name: Install Protoc
        uses: rustfs/setup-protoc@a3705324d8f9bf5b6c3573fb6cf8ae421db55dd6 # v3.0.1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create ephemeral files
        run: |
          flutter config --no-analytics &&
          dart pub global activate protoc_plugin ^21.1.2 &&
          export PATH="$PATH:$HOME/.pub-cache/bin" &&
          make flutter/prepare
      - name: Run Flutter tests
        run: make flutter/test/unit
