name: Web Deploy

on:
  push:
    branches: [ master, submission-v* ]
    paths: [ 'benchmarks_web_viewer/**' ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths: [ 'benchmarks_web_viewer/**' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build website
        env:
          REACT_APP_FIREBASE_WEB_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY }}
          REACT_APP_FIREBASE_WEB_AUTH_DOMAIN: ${{ secrets.FIREBASE_WEB_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_WEB_APP_ID: ${{ secrets.FIREBASE_WEB_APP_ID }}
          REACT_APP_FIREBASE_WEB_MEASUREMENT_ID: ${{ secrets.FIREBASE_WEB_MEASUREMENT_ID }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          cd ./benchmarks_web_viewer
          yarn install --immutable --immutable-cache --check-cache
          yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy to Firebase Hosting on Preview channel
        if: github.ref != 'refs/heads/master'
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOBILE_APP_BUILD }}"
          projectId: mobile-app-build-290400
          entryPoint: "./benchmarks_web_viewer"
          expires: 30d
      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy to Firebase Hosting on Live channel
        if: github.ref == 'refs/heads/master'
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOBILE_APP_BUILD }}"
          projectId: mobile-app-build-290400
          entryPoint: "./benchmarks_web_viewer"
          channelId: live
