include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/data/generation_helpers/edit_json_schema.main.dart
    - lib/data/generation_helpers/write_json_sample.main.dart
  language:
    strict-casts: true

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
