name: mlperfbench_common
description: A new Flutter package project.
version: 0.0.1
# homepage:

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.7.1 <3.8.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  import_sorter: ^4.6.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  json_serializable: ^6.6.2
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

import_sorter:
  comments: false
